apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'


jobs:
  ci-job:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build Go App
        uses: docker://golang:1.20
        run: |
          go build -v ./...
      - name: Run tests
        uses: docker://golang:1.20
        run: |
          go test -v ./...
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.CORINNE_DOCKER_REGISTRY }}
          username: ${{ secrets.CORINNE_DOCKER_USERNAME }}
          password: ${{ secrets.CORINNE_DOCKER_PASSWORD }}
      - name: Push image to registry
        uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ vars.CORINNE_DOCKER_REGISTRY }}/${{ secrets.CORINNE_DOCKER_USERNAME }}/my-sample-go-app:latest